WebRTC
extreal-dev/Extreal.Integration.Chat.WebRTC pull request #1
Opened 2023-08-04 06:33 UTC by kiyohome

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装

- [ ] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [ ] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました
- [ ] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました
- [ ] テストカバレッジが100%になることを確認しました
- [ ] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-08-18 12:38 UTC, sus-taguchi-t requested changes

2023-08-18 12:38 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +        private bool mute;
ミュート周りのロジックを少しいじりましたが問題ないでしょうか？
背景としては以下の事象を確認したためこれを解消するように変更をしました。

1 つのピアと P2P 通信を開始してからミュート状態を変更して、その状態でもう 1 つのピアと P2P 通信を開始したら 2 つのピアで mute 状態が別々になるという事象。

2023-08-18 12:38 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +            var inOutAudio = inOutAudioGo.AddComponent<NativeInOutAudio>();
ここだけ他 2 つと処理の順番が異なるのが気になります。

```suggestion
            var inOutAudioGo = new GameObject("InOutAudio");
            var inOutAudio = inOutAudioGo.AddComponent<NativeInOutAudio>();
            inOutAudioGo.transform.SetParent(voiceChatContainer);
```

2023-08-18 12:38 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +
空行が 2 行あることが気になります。

2023-08-18 12:38 UTC, sus-taguchi-t commented on Runtime/VoiceChatConfig.cs
> +        public bool InitialMute { get; private set; }
`private set;` は不要です。

2023-08-18 12:38 UTC, sus-taguchi-t commented on Runtime/WebGLTextChatClient.cs
> +    public class WebGLTextChatConfig
他のライブラリを見て思いましたが、JSON 用のクラスに C# ドキュメントは不要だと思います。
`WebGLVoiceChatConfig` も同様です。

2023-08-18 12:38 UTC, sus-taguchi-t commented on Runtime/WebGLTextChatClient.cs
> +        private static readonly string JsonConfig = JsonUtility.ToJson(Config);
他のライブラリに合わせて `System.Text.Json.JsonSerializer` クラスを使用した方が良いと思います。
`WebGLVoiceChatClient` も同様です。
ストリップ対策の追加も必要です。

2023-08-18 12:38 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts.meta
> +fileFormatVersion: 2
こちらと同様にディレクトリ名の末尾に `~` を付けた方が良いと思いました。
https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/1#discussion_r1296903831

2023-08-30 01:11 UTC, mahaweilu commented on Samples~/MVS/WebGLScripts.meta
> +fileFormatVersion: 2
fixed https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/1/commits/18c045166f7c10e9bf797a2720a5175eb5a5914f

2023-08-30 01:16 UTC, mahaweilu commented on Runtime/WebGLTextChatClient.cs
> +        private static readonly string JsonConfig = JsonUtility.ToJson(Config);
.JsonSerializer を使用して対応しましたが、
https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/1/commits/1599879d3bce68f10412aa60670699b82f9da53f

その後私のところで、jsconfigが空の現象が起きて、回避のため以下の修正も加えています。
https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/1/commits/5b4b5e7bd1d66644d1ed0534f2abe3392c03cf99

2023-08-30 01:17 UTC, mahaweilu commented on Runtime/WebGLTextChatClient.cs
> +    public class WebGLTextChatConfig
fixed https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/1/commits/6561385a6ce2d41dce317d229d706a2a4fb7aa38

2023-08-30 01:17 UTC, mahaweilu commented on Runtime/VoiceChatConfig.cs
> +        public bool InitialMute { get; private set; }
https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/1/commits/f06ca089ef3521d6d47bb89e6293f5565734f7ea

2023-08-30 01:18 UTC, mahaweilu commented on Runtime/NativeVoiceChatClient.cs
> +            var inOutAudio = inOutAudioGo.AddComponent<NativeInOutAudio>();
fixed https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/1/commits/0a91e92fb544cac18e0010fd0e69a4b533478ec1

2023-08-30 01:18 UTC, mahaweilu commented on Runtime/NativeVoiceChatClient.cs
> +
fixed https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/1/commits/b2f5b06e3c5244ad5b431c100483e132afeceff4

2023-08-31 02:06 UTC, mahaweilu commented on Runtime/NativeVoiceChatClient.cs
> +        private bool mute;
私のところでも事象が解消したことが確認できました。問題ないと思います。

2023-08-31 06:54 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +        private bool mute;
ありがとうございます！

2023-08-31 06:54 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +            var inOutAudio = inOutAudioGo.AddComponent<NativeInOutAudio>();
確認しました！

2023-08-31 06:55 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +
確認しました！

2023-08-31 06:55 UTC, sus-taguchi-t commented on Runtime/VoiceChatConfig.cs
> +        public bool InitialMute { get; private set; }
確認しました！

2023-08-31 06:55 UTC, sus-taguchi-t commented on Runtime/WebGLTextChatClient.cs
> +    public class WebGLTextChatConfig
確認しました！

2023-08-31 06:57 UTC, sus-taguchi-t commented on Runtime/WebGLTextChatClient.cs
> +        private static readonly string JsonConfig = JsonUtility.ToJson(Config);
確認しました！

2023-08-31 06:57 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts.meta
> +fileFormatVersion: 2
確認しました！

2023-08-31 06:58 UTC, sus-taguchi-t requested changes

2023-08-31 06:58 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts~/package.json.meta
`WebGLScripts~` 以下のメタファイルはすべて削除した方が良いと思います。

2023-09-04 00:46 UTC, mahaweilu commented on Samples~/MVS/WebGLScripts~/package.json.meta
fixed https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/1/commits/8ee51c3b19344b2a2a21997dbe016b3bf6bd12cf

2023-09-11 00:59 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts~/package.json.meta
`src` ディレクトリ以下にまだ残っています。

2023-09-11 01:42 UTC, mahaweilu commented on Samples~/MVS/WebGLScripts~/package.json.meta
fixed https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/1/commits/f532b14cddf0339fc7b2b414a62b98bb1335348a

2023-09-11 01:52 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts~/package.json.meta
確認しました。

2023-09-11 01:53 UTC, sus-taguchi-t approved these changes

2023-09-11 02:53 UTC, sus-taguchi-t submitted a review, later dismissed

2023-09-11 02:53 UTC, sus-taguchi-t commented on .gitignore
> +Samples~/MVS/WebGLScripts/node_modules*
`WebGLScripts` の末尾に `~` が入っていません。

2023-09-11 04:51 UTC, mahaweilu commented on .gitignore
> +Samples~/MVS/WebGLScripts/node_modules*
fixed https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/1/commits/5881b9a32c569915f5c5e84e02fa11c9591fc21f

2023-09-11 05:00 UTC, mahaweilu commented on .gitignore
> +Samples~/MVS/WebGLScripts/node_modules*
fixed https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/1/commits/5881b9a32c569915f5c5e84e02fa11c9591fc21f

2023-09-14 08:23 UTC, mahaweilu approved these changes

2023-09-14 08:25 UTC, merged