ボイスチャットの機能改善
extreal-dev/Extreal.Integration.Chat.WebRTC pull request #8
Opened 2023-11-26 08:07 UTC by kiyohome

# 何の変更を加えましたか？

Commitsを参照してください。
主な変更内容は下記になります。

- [ ] マイクが使えない場合はボイスチャットを聞くのみに変更
- [ ] 発話しているかを取得する機能を追加
- [ ] マイク音量を設定する機能を追加

# 何を確認しましたか?

## 実装

- [ ] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [ ] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました
- [ ] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました
- [ ] テストカバレッジが100%になることを確認しました
- [ ] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-12-20 07:31 UTC, mahaweilu commented on Runtime/NativeVoiceChatClient.cs
> +            Observable.EveryUpdate()
指摘ではなく、コメントだけですが、フレームごとにハンドルするので性能面に影響を与えるかなと思いましたが、一般的な実装もこうなっているなら大丈夫と思います。

2023-12-20 09:26 UTC, sus-taguchi-t requested changes

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> -            while (!(Microphone.GetPosition(null) > 0))
この処理はなくしても良いのでしょうか？

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +                // Not covered by testing due to defensive implementation
マイクがない端末で動作するときに通ると思うので defensive implementation ではないように思います。
またマイクなし端末でテストすれば通るので Not covered by testing でもないように思います。

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
>          public override void Clear()
Clear 時にオーディオの音量を初期値に戻さなくて良いでしょうか？

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +            if (!string.IsNullOrEmpty(ownId))
```csharp
if (string.IsNullOrEmpty(ownId))
{
    return;
}
```

とした方が読みやすくなると思います。

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +                audioLevelList.Clear();
```csharp
previousAudioLevelList = new Dictionary<string, float>(audioLevelList);
audioLevelList.Clear();
```

とすればすっきりすると思います。

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +                        audioLevel = GetAudioLevel(outAudio);
同じ変数を違う用途で使いまわしているのに違和感があります。
別々の変数にしてはいけないでしょうか？

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +                        audioLevel = GetAudioLevel(outAudio);
もしくは変数を使用せず直接代入ではいけないでしょうか？

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +        private readonly Dictionary<string, float> previousAudioLevelList = new Dictionary<string, float>();
フィールドとして保持しておく必要はあるでしょうか？

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +                    audioLevelList[ownId] = audioLevel;
マイクが使えない場合にこのあたりの処理でエラーにならないでしょうか？

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/VoiceChatClient.cs
> +        /// <para>Invokes update timing if audio levels are changed.</para>
Invokes update timing if audio levels are changed.
-> Invokes at the time of Update immediately after the audio level has been changed.

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/VoiceChatClient.cs
> +        /// Returns whether or not a microphone is available.
Returns whether or not a microphone is available.
-> Returns whether a microphone is available or not.

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/VoiceChatClient.cs
> +        /// <param name="volume">volume to set (0.0 - 1.0)</param>
volume to set
-> volume to be set

SetOutVolume も同様です。

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/VoiceChatConfig.cs
> +
不要な空行だと思います。

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/VoiceChatConfig.cs
>          /// <param name="initialMute">True if initial muted, false otherwise.</param>
param タグが増えていないです。

2023-12-20 09:26 UTC, sus-taguchi-t commented on Runtime/WebGLVoiceChatClient.cs
> +        private static void HandleOnAudioLevelChanged(string audioLevelsListStr, string unused)
audioLevelsListStr -> audioLevelListStr

2023-12-20 09:26 UTC, sus-taguchi-t commented on WebScripts~/src/VoiceChatClient.ts
オーディオの音量関連の内容について参考にした資料等があれば PR の説明に書いておいてほしいです。

2023-12-20 09:26 UTC, sus-taguchi-t commented on WebScripts~/src/VoiceChatClient.ts
> +            if (this.audioContext === undefined)
```typescript
if (!this.audioContext)
```

ではいけないでしょうか？

2023-12-21 02:46 UTC, sasuke9410 requested changes

2023-12-21 02:46 UTC, sasuke9410 commented on Runtime/NativeVoiceChatClient.cs
> +                    if (!audioLevelList.ContainsKey(id) || audioLevelList[id] != previousAudioLevelList[id])
ここで音量レベルの変化を比較して出力していると思います。
float型同士の比較だと完全に一致することはなかなかないと思うので、
閾値(threshold)を定義して、
Math.Abs(audioLevelList[id] - previousAudioLevelList[id]) > threshold で
ある程度の音量変化があった場合のみTrueにするのはどうでしょうか？

2023-12-21 02:46 UTC, sasuke9410 commented on Samples~/MVS/ClientControl/ClientControl.unity
> -      value: NetworkManager
ClientControlシーンからGameObjectの削除を行ったようですが、なにを行ったのでしょうか？
MissingになっていたNetworkManagerの削除？

2023-12-21 07:50 UTC, sus-yoshikane-t commented on Samples~/MVS/ClientControl/ClientControl.unity
> -      value: NetworkManager
不要な（Missingになっていた）NetworkManagerの削除です。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/commit/cc311ce7381f12d0410a352660af4d07134d02cc

2023-12-21 08:12 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> -            while (!(Microphone.GetPosition(null) > 0))
マイクがない場合に処理が返ってこなくなるため削除しています。

2023-12-21 08:39 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +                audioLevelList.Clear();
DictionaryのnewでGC.Allocされないようにこの書き方にしています。

2023-12-21 08:56 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +        private readonly Dictionary<string, float> previousAudioLevelList = new Dictionary<string, float>();
DictionaryのnewでGC.Allocされないように保持しています。

2023-12-21 09:50 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +            Observable.EveryUpdate()
確かに人数が増えれば増えるだけ性能面での影響が大きそうなため、頻度の設定が将来的にあると良いような気はします。

2023-12-21 10:00 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +                // Not covered by testing due to defensive implementation
修正しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/7d1e5dfadf1d68d3fd053a14116f05926ce658ec

2023-12-21 10:01 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
>          public override void Clear()
戻す必要があるため修正しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/c22f8ebd3165052ebae6baf325d2fb07bba82ccc

2023-12-21 10:01 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +            if (!string.IsNullOrEmpty(ownId))
修正しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/dcda5daa4fc7d2417991dd22d5a67d54ff7bbb2f

2023-12-21 10:02 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +                        audioLevel = GetAudioLevel(outAudio);
別々の変数に修正しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/a58c15fdb6aff80b89363ea6b1eca5b8a707a486

2023-12-21 10:02 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +                    audioLevelList[ownId] = audioLevel;
修正しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/131d666dea4b6900fcb1984e35da208abed356c0

2023-12-21 10:03 UTC, sus-yoshikane-t commented on Runtime/VoiceChatClient.cs
> +        /// <para>Invokes update timing if audio levels are changed.</para>
修正しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/8492de8b8c2faaa7337cc68d4f7479fcf5f51ef0

2023-12-21 10:03 UTC, sus-yoshikane-t commented on Runtime/VoiceChatClient.cs
> +        /// Returns whether or not a microphone is available.
修正しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/8492de8b8c2faaa7337cc68d4f7479fcf5f51ef0

2023-12-21 10:04 UTC, sus-yoshikane-t commented on Runtime/VoiceChatClient.cs
> +        /// <param name="volume">volume to set (0.0 - 1.0)</param>
修正しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/8492de8b8c2faaa7337cc68d4f7479fcf5f51ef0

2023-12-21 10:04 UTC, sus-yoshikane-t commented on Runtime/VoiceChatConfig.cs
> +
削除しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/679a33bfff83a5d3621e85371c247dcbf664fd39

2023-12-21 10:04 UTC, sus-yoshikane-t commented on Runtime/VoiceChatConfig.cs
>          /// <param name="initialMute">True if initial muted, false otherwise.</param>
追加しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/8492de8b8c2faaa7337cc68d4f7479fcf5f51ef0

2023-12-21 10:05 UTC, sus-yoshikane-t commented on Runtime/WebGLVoiceChatClient.cs
> +        private static void HandleOnAudioLevelChanged(string audioLevelsListStr, string unused)
修正しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/5660a46d91db514b1b1f309e4960a408be4efad8

2023-12-21 10:05 UTC, sus-yoshikane-t commented on WebScripts~/src/VoiceChatClient.ts
> +            if (this.audioContext === undefined)
問題ないため修正しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/9a5da0dda17ca108f8315b8d7f6306394d8c650f

2023-12-21 11:33 UTC, sasuke9410 commented on Samples~/MVS/ClientControl/ClientControl.unity
> -      value: NetworkManager
ありがとうございます。
問題ありません

2023-12-22 02:31 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> -            while (!(Microphone.GetPosition(null) > 0))
```csharp
if (Microphone.devices.Length > 0)
```

ここの判定でマイクがない場合は弾かれるので問題ないと思ったのですが、そうではないのでしょうか？

2023-12-22 02:32 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +                // Not covered by testing due to defensive implementation
確認しました。

2023-12-22 02:32 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
>          public override void Clear()
確認しました。

2023-12-22 02:33 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +            if (!string.IsNullOrEmpty(ownId))
確認しました。

2023-12-22 02:43 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +                audioLevelList.Clear();
分かりました。

2023-12-22 02:43 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +                        audioLevel = GetAudioLevel(outAudio);
確認しました。

2023-12-22 02:44 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +        private readonly Dictionary<string, float> previousAudioLevelList = new Dictionary<string, float>();
分かりました。

2023-12-22 02:49 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +                    audioLevelList[ownId] = audioLevel;
確認しました。

2023-12-22 02:49 UTC, sus-taguchi-t commented on Runtime/VoiceChatClient.cs
> +        /// <para>Invokes update timing if audio levels are changed.</para>
確認しました。

2023-12-22 02:50 UTC, sus-taguchi-t commented on Runtime/VoiceChatClient.cs
> +        /// <param name="volume">volume to set (0.0 - 1.0)</param>
確認しました。

2023-12-22 02:50 UTC, sus-taguchi-t commented on Runtime/VoiceChatConfig.cs
> +
確認しました。

2023-12-22 02:50 UTC, sus-taguchi-t commented on Runtime/VoiceChatConfig.cs
>          /// <param name="initialMute">True if initial muted, false otherwise.</param>
確認しました。

2023-12-22 02:51 UTC, sus-taguchi-t commented on Runtime/WebGLVoiceChatClient.cs
> +        private static void HandleOnAudioLevelChanged(string audioLevelsListStr, string unused)
確認しました。

2023-12-22 02:51 UTC, sus-taguchi-t commented on WebScripts~/src/VoiceChatClient.ts
> +            if (this.audioContext === undefined)
確認しました。

2023-12-22 05:09 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +            Observable.EveryUpdate()
Vivoxでは頻度が設定できる（選べる）ようになっていたため、頻度が設定できるように修正を行います。（[参考](https://support.unity.com/hc/en-us/articles/4826715847572-Vivox-How-do-I-change-the-participant-property-frequency-)）

2023-12-28 08:31 UTC, sus-yoshikane-t commented on WebScripts~/src/VoiceChatClient.ts
追記しました。

2023-12-28 08:33 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> -            while (!(Microphone.GetPosition(null) > 0))
弾かれて問題ないため修正しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/99666b3548bc9022b419c1e85daf04c630a00a89

2024-01-10 02:04 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +            Observable.EveryUpdate()
頻度が設定できるように修正を行いました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/cc680ce82b976762f7225db908d430e1275478b9 https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/deddaa20259489f10e56fc4040ca998563159498 https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/2b2f9bc2ccf88e36e641e27a009d1b5d8eb93f3a

2024-01-12 01:01 UTC, sus-taguchi-t requested changes

2024-01-12 01:01 UTC, sus-taguchi-t commented on Runtime/VoiceChatConfig.cs
> +        public float InitialAudioLevelCheckIntervalSeconds { get; }
C# ドキュメント追記をお願いします。

2024-01-12 01:01 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +            audioLevelCheckIntervalSeconds = voiceChatConfig.InitialAudioLevelCheckIntervalSeconds;
`audioLevelCheckIntervalSeconds` というフィールドに `voiceChatConfig.InitialAudioLevelCheckIntervalSeconds` の値を代入して使用していますが、この `audioLevelCheckIntervalSeconds` の値を途中で変更する API を用意しないのであれば `VoiceChatConfig` クラスの `InitialAudioLevelCheckIntervalSeconds` フィールドでは "Initial" を付けなくて良いと思います。

2024-01-12 01:02 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> -            while (!(Microphone.GetPosition(null) > 0))
確認しました。

2024-01-12 01:03 UTC, sus-taguchi-t commented on WebScripts~/src/VoiceChatClient.ts
ありがとうございます！
確認しました。

2024-01-12 01:49 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +            audioLevelCheckIntervalSeconds = voiceChatConfig.InitialAudioLevelCheckIntervalSeconds;
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/58d3e7aaa72329715e14ea2da3f4075580017c5f

2024-01-12 01:51 UTC, sus-yoshikane-t commented on Runtime/VoiceChatConfig.cs
> +        public float InitialAudioLevelCheckIntervalSeconds { get; }
追記しました。
https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/efd6f7b8780abfa43a110eb7187e69e61702eb6c

2024-01-12 01:54 UTC, sus-taguchi-t commented on Runtime/VoiceChatConfig.cs
> +        public float InitialAudioLevelCheckIntervalSeconds { get; }
確認しました。

2024-01-12 01:56 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +            audioLevelCheckIntervalSeconds = voiceChatConfig.InitialAudioLevelCheckIntervalSeconds;
確認しました。

2024-01-12 01:57 UTC, sus-taguchi-t requested changes

2024-01-12 01:57 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +        private readonly float audioLevelCheckIntervalSeconds;
`audioLevelCheckIntervalSeconds` はフィールドとして保持する必要はないと思います。
ts も同様です。

2024-01-12 02:05 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +        private readonly float audioLevelCheckIntervalSeconds;
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/d6e3c430a56e54bcc72f59000ae38a365db408d0

2024-01-12 02:06 UTC, sus-taguchi-t commented on Runtime/NativeVoiceChatClient.cs
> +        private readonly float audioLevelCheckIntervalSeconds;
確認しました。

2024-01-12 02:34 UTC, sus-taguchi-t approved these changes

2024-01-25 08:31 UTC, kiyohome commented on Runtime/NativeVoiceChatClient.cs
> +        private readonly Dictionary<string, float> audioLevelList = new Dictionary<string, float>();
xxxxListはあまり使ってないと思います。複数形がよくないでしょうか？

2024-01-25 09:17 UTC, kiyohome commented on Runtime/VoiceChatClient.cs
> +        public IObservable<IReadOnlyDictionary<string, float>> OnAudioLevelChanged => onAudioLevelChanged.AddTo(Disposables);
個別に渡さず、Dictionaryにしている理由はありますか？

2024-01-25 09:17 UTC, kiyohome commented on Runtime/NativeVoiceChatClient.cs
> +        private void AudioLevelChangeHandler()
処理フローが分かりにくいので、処理をメソッド分割したら、このメソッドを見たら何をやってるかすぐに分かるかと思います。

2024-01-25 09:17 UTC, kiyohome commented on Runtime/NativeVoiceChatClient.cs
> +            return audioLevel;
AudioLevelは概念の名前として合ってますか？

2024-01-25 09:17 UTC, kiyohome commented on WebScripts~/src/VoiceChatClient.ts
> +        const audioContextResumeFunc = () => {
イベント起きたら一度だけ処理を実行して、終わったらイベント解除する関数に切り出した方がいいと思います。

2024-01-25 11:07 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +        private readonly Dictionary<string, float> audioLevelList = new Dictionary<string, float>();
修正しました。 https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/a67a6334d963e4ee68268f55ec092b81f553107b

2024-01-25 11:08 UTC, sus-yoshikane-t commented on Runtime/VoiceChatClient.cs
> +        public IObservable<IReadOnlyDictionary<string, float>> OnAudioLevelChanged => onAudioLevelChanged.AddTo(Disposables);
個別に渡すで特に問題ないため修正しました。 https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/8fd9812a503daaffddbe6a84aa8a7489793455e1

2024-01-25 11:09 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +        private void AudioLevelChangeHandler()
修正しました。 https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/8fd9812a503daaffddbe6a84aa8a7489793455e1

2024-01-26 04:24 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +            return audioLevel;
WebRTCでは[`audioLevel`](https://developer.mozilla.org/en-US/docs/Web/API/RTCAudioSourceStats/audioLevel)の名前を使用しているようです。（全期間では[`totalAudioEnergy`](https://developer.mozilla.org/en-US/docs/Web/API/RTCAudioSourceStats/totalAudioEnergy)になるようですが。）

（上記は実験的なプロパティであり対応していないブラウザもありますが、将来対応された際には置き換えができるかもしれません。）

2024-01-26 04:24 UTC, sus-yoshikane-t commented on WebScripts~/src/VoiceChatClient.ts
> +        const audioContextResumeFunc = () => {
修正しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/f2ed542e75da95ce1264c0850ebbccdd356b2e11

2024-01-26 07:38 UTC, kiyohome commented on Runtime/NativeVoiceChatClient.cs
> +        private void AudioLevelChangeHandler()
AudioLevelChangeHandlerはメソッドだと思うんですが、動詞始まりにしてない理由はありますか？
イベントに+=で代入するものであればHandlerでもいいですが、呼び出すものは動詞始まりに統一しませんか？
InAudioLevelChangeHandlerとかも。

2024-01-26 07:38 UTC, kiyohome commented on Runtime/NativeVoiceChatClient.cs
> +            return audioLevel;
了解です！

2024-01-26 07:42 UTC, kiyohome commented on WebScripts~/src/VoiceChatClient.ts
> +        const audioContextResume = () => {
audioContextResumeは関数なので、resumeAudioContextの方がよくないでしょうか？

2024-01-26 08:19 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +        private void AudioLevelChangeHandler()
修正しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/412419e1868bfa3c38c4e0852b29145faf40df2b
また、C#とTypeScriptでメソッド名が揃っていなかった部分を揃えました。

2024-01-26 08:20 UTC, sus-yoshikane-t commented on WebScripts~/src/VoiceChatClient.ts
> +        const audioContextResume = () => {
修正しました。https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/commits/412419e1868bfa3c38c4e0852b29145faf40df2b

2024-01-26 08:47 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +                    if (!audioLevelList.ContainsKey(id) || audioLevelList[id] != previousAudioLevelList[id])
閾値が必要な場合はライブラリ側でなく、利用者側で処理してもらう方針になりました。

2024-01-26 08:51 UTC, sasuke9410 approved these changes

2024-01-26 08:56 UTC, merged